### ISSUE TITLE
 Issue with Item Rack Not Appearing

### ISSUE THREAD

**Issue by marrudagg** [citRaTTV/citra_weed#2]
Hello,

I am currently experiencing an issue with the script. Specifically, when I use the item to deploy the rack, it does not appear at all. I have followed the setup instructions, but the functionality seems to be broken.

Could you please provide any guidance or possible fixes for this issue? Any help would be greatly appreciated.

Thank you!

**Comment by citRaTTV** [comment]
> Hello,
> 
> I am currently experiencing an issue with the script. Specifically, when I use the item to deploy the rack, it does not appear at all. I have followed the setup instructions, but the functionality seems to be broken.
> 
> Could you please provide any guidance or possible fixes for this issue? Any help would be greatly appreciated.
> 
> Thank you!

What inventory system are you using? If you're not seeing an animation or an object, it sounds like the item isn't setup properly.
